###
# api/course
###

GET http://localhost:8000/api/course

###

GET    http://localhost:8000/api/course/1

###

PUT    http://localhost:8000/api/course/3
content-type: application/json

{
  "name": "UI/UX Design"
}

###

POST http://localhost:8000/api/course
content-type: application/json

{
  "name": "new course name"
}

###

DELETE http://localhost:8000/api/course/38

###
# api/student
###

GET    http://localhost:8000/api/student

###

GET    http://localhost:8000/api/student/Barack

###

PUT    http://localhost:8000/api/student/David
content-type: application/json

{
  "first_name": "Barack",
  "last_name": "Obama",
  "type": "student",
  "age": 24,
  "courses": [
    1
  ]
}

###

POST http://localhost:8000/api/student
content-type: application/json

{
  "first_name": "first_name",
  "last_name": "last_name",
  "type": "professor",
  "age": 10,
  "courses": [
    1,
    2
  ]
}

###

DELETE http://localhost:8000/api/student/Barack



###
# api/professor
###

GET    http://localhost:8000/api/professor

###

GET    http://localhost:8000/api/professor/Steve

###

PUT    http://localhost:8000/api/professor/David
content-type: application/json

{
  "first_name": "Joe",
  "last_name": "Biden",
  "type": "professor",
  "age": 30,
  "courses": [
    1
  ]
}

###

POST http://localhost:8000/api/professor
content-type: application/json

{
  "first_name": "David",
  "last_name": "Choi",
  "type": "professor",
  "age": 14,
  "courses": [
    2
  ]
}

###

DELETE http://localhost:8000/api/professor/Joe

###